### ISSUE TITLE
Additional org owner(s)

### ISSUE THREAD

**Issue by efiop** [fsspec/community#3]
Currently, there is only one owner https://github.com/orgs/fsspec/people , which means that if @martindurant for some reason becomes unavailable, no one else will be able to do org-level actions (e.g. inviting people, changing teams, granting permissions to repositories, adopting new repos that are being transfered from elsewhere, etc), which is a problem. I think we should have at least one more owner for everyone's security.

From https://github.com/fsspec/sshfs/issues/13

**Comment by martindurant** [comment]
I had thought that setting up the team would achieve this, but apparently not. I am happy to add all members of the team as owners of the org (making the team redundant, I suppose), or specific people as nominated here.
Any thoughts? cc @fsspec/maintainers 

In addition, we should consider who should hold rights to pypi, conda-forge and RTD.

**Comment by efiop** [comment]
Looks like conda-forge has a bunch of owners as well https://github.com/orgs/conda-forge/people?query=role%3Aowner, including `conda-forge-admin`. Though they have a very advanced system at this point.

> making the team redundant, I suppose

Still very useful for mentioning and for, well, adding people to maintainers and not org owners 🙂 I think we should create `admins` team in addition to `maintainers` for conveniently mentioning org owners.

> In addition, we should consider who should hold rights to pypi, conda-forge and RTD.

All org owners (aka admins) need to be added to those, I believe. For the same reasons as having multiple owners of this org. This might become a security concern at a certain number of people though, so we should find a balance.

Whichever way we go, I think I should nominate myself

![image](https://user-images.githubusercontent.com/5367102/142475624-40e306ea-842d-42df-9b76-8b1fb296f778.png)

to be added , as I'm pretty much directly or indirectly managing all of the fsspec-related work at iterative (sshfs, ossfs, pydrive2, gitfs etc) and I'm happy to serve as an emergency backup for other repos. 🙂

**Comment by martindurant** [comment]
I added all the maintainers team as owners (I think!).

**Comment by efiop** [comment]
@martindurant Thanks! Closing since this is resolved. Created https://github.com/fsspec/community/issues/4 for pypi/conda/rtd discussion.
