### ISSUE TITLE
Idea for a CLI utility similar to curl, wget or rsync

### ISSUE THREAD

**Issue by timsnyder** [fsspec/community#7]
@efiop &  @martindurant, I'm interested in having a CLI utility that brings the power of fsspec to an interface similar to curl, wget or rsync.

Have you guys thought about anything like this?  Would you be interested in having something like this be a part of the fsspec community of repos?  I'm open to having it be completely separate to start but if it's something you guys know already exists and I'm just not finding it, I'd rather not write yet another python package. Thanks.

**Comment by martindurant** [comment]
Sounds like a good idea to me. You maybe would start by looking in fsspec.generic (where there already is an rsync function). We would be happy to see this in the fsspec org as a separate repo/package once it is ready. 
The trickiest part is probably deciging how to deal with configuration. Perhaps everythng needs to be done by environment variables (so https://github.com/fsspec/filesystem_spec/pull/1194 might help).

**Comment by timsnyder** [comment]
Thanks for the pointers @martindurant!
